# Generated by Django 4.0.5 on 2022-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='facebook_id',
            field=models.URLField(blank=True),
        ),
    ]
