# Generated by Django 4.0.5 on 2022-06-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='num_stars',
            new_name='rating',
        ),
    ]
